CREATE TABLE [dbo].[UserSession]
(
	[id] [int] IDENTITY(1,1) NOT NULL,
	[userid] [varchar](100)  NOT NULL,
	[sessionid] varchar(100) NULL,
 CONSTRAINT [PK_UserSession] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]